-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "renderPosX" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "renderPosY" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "sketchPosX" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "sketchPosY" INTEGER NOT NULL DEFAULT 50;
